#!/usr/bin/env bash

#   keytemp V0.0.1 -- Add Temporary SSH Public Key to user account.
#   Copyright (C) 2017 Mark Coccimiglio <mcoccimiglio@rice.edu>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

#   This file is used to make a USB Key Fob using pass-phrase protected
#   ssh Private Key(s) for local login.

#   Required packages for this script:
#   TBD
